version: '3.8'

services:
#  redis:
#    image: redis:latest
#    container_name: redis-for-rut-cloud
#    ports:
#      - "6379:6379"
#    restart: always
  sqlite:
    image: alpine
    volumes:
      - ./data:/data
    command: >
      sh -c "
        apk add --no-cache sqlite;
        sqlite3 /data/database.sqlite;
      "
