#spring.servlet.multipart.max-file-size=128KB
#spring.servlet.multipart.max-request-size=128KB
server.port=8090

# ????????? ??? ??????????? ? Minio
minio.endpoint=http://localhost:9000
minio.accessKey=access_key
minio.secretKey=secret_key
minio.bucketName=my-bucket
