#spring.servlet.multipart.max-file-size=128KB
#spring.servlet.multipart.max-request-size=128KB
server.port=8090


spring.datasource.url=jdbc:sqlite:/data/database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect





## ????????? ??? ??????????? ? Minio
#minio.endpoint=http://localhost:9000
#minio.accessKey=access_key
#minio.secretKey=secret_key
#minio.bucketName=my-bucket
